[platformio]
description=Smart_Hybrid_IOT_energy_management_System

default_envs = esp32dev

[env:esp32dev]
platform = espressif32@6.5.0
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    olikraus/U8g2@^2.36.17
    mandulaj/PZEM-004T-v30 @ ^1.1.2
build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=0
