[platformio]
description=Solar_Powered Egg_Incubator

[env:esp32dev]
platform = espressif32@6.5.0
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    olikraus/U8g2@^2.36.5
    adafruit/Adafruit AHTX0@^2.0.5
    adafruit/RTClib@^2.1.4
build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=0
    -DARDUINO_ENABLE_PERIPHERAL_MANAGER=1
    -Ilib/Pins
    -Ilib/Power/battery_level
    -Ilib/Power/solar_level
    -Ilib/Sensors/ultrasonic
    -Ilib/Sensors/temp_hum
    -Ilib/Input/rotary_encoder
    -Ilib/Actuators/buzzer
    -Ilib/Actuators/fan
    -Ilib/Actuators/heater
    -Ilib/Actuators/spinner
    -Ilib/Actuators/humidifier
    -Ilib/Display/led_indicator
    -Ilib/Display/lcd_screen
    -Ilib/Communication/wifi_manager
    -Ilib/Communication/web_dashboard
    -Ilib/Control/error_handling
    -Ilib/Control/sleep_wake
    -Ilib/System/reset
    -Ilib/System/rtc_clock
