[platformio]
description = Fingerprint_and_RFID_Card_Attendance_System

[env:esp32-s3-devkitm-1]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
board_build.partitions = huge_app.csv

lib_deps =
    adafruit/Adafruit NeoPixel
    olikraus/U8g2
    adafruit/RTClib
    adafruit/Adafruit Fingerprint Sensor Library
    miguelbalboa/MFRC522
    adafruit/Adafruit BusIO

build_flags =
    -DARDUINO_USB_MODE=1

    -DARDUINO_USB_CDC_ON_BOOT=1
    -Ilib/Pins
    -Ilib/Actuators
    -Ilib/Communication
    -Ilib/Control
    -Ilib/Display
    -Ilib/Input
    -Ilib/Power
    -Ilib/Sensors
    -Ilib/Storage
    -Ilib/System
