[platformio]
description=Smart_Transformer_Health_Monitoring_System

[env:esp32-s3-devkitm-1]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino
monitor_speed = 115200

lib_deps =
    marcoschwartz/LiquidCrystal_I2C@^1.1.4
    adafruit/Adafruit ADXL345@^1.3.4
    adafruit/Adafruit Unified Sensor@^1.1.14
    paulstoffregen/OneWire@^2.3.8
    milesburton/DallasTemperature@^3.11.0

build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=0
    -DARDUINO_ENABLE_PERIPHERAL_MANAGER=1
